[program:netgazer-server]
command=/usr/local/bin/netgazer-server --http-port=8080 --grpc-port=50051 --db=/var/lib/netgazer/netgazer.db --web-dir=/opt/netgazer/frontend/dist
user=netgazer
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
